"""Update model penyakit and gejala

Revision ID: 000a94037fd8
Revises: d7668374117f
Create Date: 2022-08-20 14:58:56.632302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000a94037fd8'
down_revision = 'd7668374117f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gejala', sa.Column('kode', sa.String(length=5), nullable=True))
    op.create_unique_constraint(None, 'gejala', ['kode'])
    op.add_column('penyakit', sa.Column('kode', sa.String(length=5), nullable=True))
    op.create_unique_constraint(None, 'penyakit', ['kode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'penyakit', type_='unique')
    op.drop_column('penyakit', 'kode')
    op.drop_constraint(None, 'gejala', type_='unique')
    op.drop_column('gejala', 'kode')
    # ### end Alembic commands ###
