"""Create model penyakit and gejala

Revision ID: 1524e038c067
Revises: c00c7a97eacc
Create Date: 2022-08-20 14:25:29.349509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1524e038c067'
down_revision = 'c00c7a97eacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gejala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gejala', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penyakit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penyakit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relasi',
    sa.Column('penyakit_id', sa.Integer(), nullable=True),
    sa.Column('gejala_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gejala_id'], ['gejala.id'], ),
    sa.ForeignKeyConstraint(['penyakit_id'], ['penyakit.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relasi')
    op.drop_table('penyakit')
    op.drop_table('gejala')
    # ### end Alembic commands ###
