"""empty message

Revision ID: 245a8386abf1
Revises: d2b739e384df
Create Date: 2022-08-18 16:47:47.948141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245a8386abf1'
down_revision = 'd2b739e384df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.Enum('admin', 'pakar', name='Tipe Pengguna'), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
