"""empty message

Revision ID: 629f71250dea
Revises: 000a94037fd8
Create Date: 2022-08-26 15:08:05.010736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629f71250dea'
down_revision = '000a94037fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pohon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pohon')
    # ### end Alembic commands ###
