"""empty message

Revision ID: 6c181378c1ac
Revises: d1e1e44368bc
Create Date: 2022-08-30 21:04:34.690300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c181378c1ac'
down_revision = 'd1e1e44368bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_config', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_config', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
