"""empty message

Revision ID: 6ebba809d000
Revises: 629f71250dea
Create Date: 2022-08-26 15:20:24.770005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebba809d000'
down_revision = '629f71250dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pohon', sa.Column('id_gejala', sa.Integer(), nullable=True))
    op.add_column('pohon', sa.Column('id_penyakit', sa.Integer(), nullable=True))
    op.add_column('pohon', sa.Column('id_left', sa.Integer(), nullable=True))
    op.add_column('pohon', sa.Column('id_right', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pohon', 'penyakit', ['id_penyakit'], ['id'])
    op.create_foreign_key(None, 'pohon', 'pohon', ['id_left'], ['id'])
    op.create_foreign_key(None, 'pohon', 'pohon', ['id_right'], ['id'])
    op.create_foreign_key(None, 'pohon', 'gejala', ['id_gejala'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pohon', type_='foreignkey')
    op.drop_constraint(None, 'pohon', type_='foreignkey')
    op.drop_constraint(None, 'pohon', type_='foreignkey')
    op.drop_constraint(None, 'pohon', type_='foreignkey')
    op.drop_column('pohon', 'id_right')
    op.drop_column('pohon', 'id_left')
    op.drop_column('pohon', 'id_penyakit')
    op.drop_column('pohon', 'id_gejala')
    # ### end Alembic commands ###
