"""empty message

Revision ID: 74417faa6c13
Revises: 02b65d36eca3
Create Date: 2023-03-29 21:05:59.944524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74417faa6c13'
down_revision = '02b65d36eca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penyakit', sa.Column('data', sa.LargeBinary(), nullable=False))
    op.add_column('penyakit', sa.Column('rendered_data', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('penyakit', 'rendered_data')
    op.drop_column('penyakit', 'data')
    # ### end Alembic commands ###
