"""empty message

Revision ID: 7fffa95c13f0
Revises: 9ba59c1ca948
Create Date: 2023-04-07 23:16:45.686681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fffa95c13f0'
down_revision = '9ba59c1ca948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_diagnosa_usertelegram_id_fkey', 'history_diagnosa', type_='foreignkey')
    op.create_foreign_key(None, 'history_diagnosa', 'usertelegram', ['usertelegram_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('proses_diagnosa_history_id_fkey', 'proses_diagnosa', type_='foreignkey')
    op.create_foreign_key(None, 'proses_diagnosa', 'history_diagnosa', ['history_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proses_diagnosa', type_='foreignkey')
    op.create_foreign_key('proses_diagnosa_history_id_fkey', 'proses_diagnosa', 'history_diagnosa', ['history_id'], ['id'])
    op.drop_constraint(None, 'history_diagnosa', type_='foreignkey')
    op.create_foreign_key('history_diagnosa_usertelegram_id_fkey', 'history_diagnosa', 'usertelegram', ['usertelegram_id'], ['id'])
    # ### end Alembic commands ###
