"""empty message

Revision ID: 88704029b966
Revises: 245a8386abf1
Create Date: 2022-08-18 16:48:07.879989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88704029b966'
down_revision = '245a8386abf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.Enum('admin', 'pakar', name='user_type'), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
