"""empty message

Revision ID: 99a1d59ff912
Revises: 74417faa6c13
Create Date: 2023-03-29 21:07:44.692272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a1d59ff912'
down_revision = '74417faa6c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penyakit', sa.Column('data', sa.LargeBinary(), nullable=True))
    op.add_column('penyakit', sa.Column('rendered_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('penyakit', 'rendered_data')
    op.drop_column('penyakit', 'data')
    # ### end Alembic commands ###
