"""empty message

Revision ID: 9ba59c1ca948
Revises: 99a1d59ff912
Create Date: 2023-04-07 16:51:39.126984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba59c1ca948'
down_revision = '99a1d59ff912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertelegram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_bot', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_bot')
    )
    op.create_table('history_diagnosa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usertelegram_id', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('hasil', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['usertelegram_id'], ['usertelegram.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proses_diagnosa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('gejala', sa.String(length=64), nullable=True),
    sa.Column('respon', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history_diagnosa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proses_diagnosa')
    op.drop_table('history_diagnosa')
    op.drop_table('usertelegram')
    # ### end Alembic commands ###
