"""empty message

Revision ID: a81aff0bea1d
Revises: 6ebba809d000
Create Date: 2022-08-26 15:33:29.015934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81aff0bea1d'
down_revision = '6ebba809d000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pohon', sa.Column('gejala', sa.String(length=50), nullable=True))
    op.add_column('pohon', sa.Column('penyakit', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pohon', 'penyakit')
    op.drop_column('pohon', 'gejala')
    # ### end Alembic commands ###
