"""Update model penyakit and gejala

Revision ID: d7668374117f
Revises: 1524e038c067
Create Date: 2022-08-20 14:34:54.576773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7668374117f'
down_revision = '1524e038c067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gejala', sa.Column('deskripsi', sa.Text(), nullable=True))
    op.add_column('penyakit', sa.Column('deskripsi', sa.Text(), nullable=True))
    op.add_column('penyakit', sa.Column('penanganan', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('penyakit', 'penanganan')
    op.drop_column('penyakit', 'deskripsi')
    op.drop_column('gejala', 'deskripsi')
    # ### end Alembic commands ###
