"""empty message

Revision ID: da4eb65fbfb7
Revises: a81aff0bea1d
Create Date: 2022-08-26 16:07:43.775022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4eb65fbfb7'
down_revision = 'a81aff0bea1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pohon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pohon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_gejala', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_penyakit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_left', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_right', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gejala', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('penyakit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_gejala'], ['gejala.id'], name='pohon_id_gejala_fkey'),
    sa.ForeignKeyConstraint(['id_left'], ['pohon.id'], name='pohon_id_left_fkey'),
    sa.ForeignKeyConstraint(['id_penyakit'], ['penyakit.id'], name='pohon_id_penyakit_fkey'),
    sa.ForeignKeyConstraint(['id_right'], ['pohon.id'], name='pohon_id_right_fkey'),
    sa.PrimaryKeyConstraint('id', name='pohon_pkey')
    )
    # ### end Alembic commands ###
